CREATE DATABASE ORG;
USE ORG;
CREATE TABLE Worker (
    WORKER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME CHAR(25),
    LAST_NAME CHAR(25),
    SALARY INT(15),
    JOINING_DATE DATE,
    DEPARTMENT CHAR(25)
);
INSERT INTO Worker (FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES
('Monika', 'Arora', 100000, '2020-02-14', 'HR'),
('Niharika', 'Verma', 80000, '2011-06-14', 'Admin');
START TRANSACTION;
INSERT INTO Worker (FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT)
VALUES ('Amit', 'Sharma', 70000, '2020-03-12 10:00:00', 'Finance');
SAVEPOINT sp1;
INSERT INTO Worker (FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT)
VALUES ('Priya', 'Kumari', 60000, '2020-05-21 11:30:00', 'HR');
ROLLBACK TO sp1;
COMMIT;
SELECT * FROM Worker;
